baseURL = "https://blog.gatosyocora.net/"
title = "がとーしょこらのブログ"
theme = "zzo"

# defaultContentLanguage = "ja"

copyright = "Copyright © 2021, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 10

languageCode = 'ja'
publishDir = 'docs'
# canonifyurls = true
disqusShortname = ""

# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
