# canonifyurls = true
paginate = 10
theme = "hugo-clarity"
disqusShortname = ""

# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
