baseURL = "https://blog.gatosyocora.net/"
title = "がとーしょこらのブログ"
theme = "zzo"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

summaryLength = 70
buildFuture = true

copyright = "Copyright © 2021, Steve Francia and the Hugo Authors; all rights reserved."
timeout = 30000
enableEmoji = true
paginate = 10
rssLimit = 100

enableGitInfo = false
googleAnalytics = "G-KP1JBN07MT"

languageCode = 'ja'
publishDir = 'docs'
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
