baseURL = 'https://blog.gatosyocora.net/'
languageCode = 'ja'
# DefaultContentLanguage = "ja"
title = 'がとーしょこらのブログ'
copyright = "Copyright © 2021, Steve Francia and the Hugo Authors; all rights reserved."
publishDir = 'docs'

# canonifyurls = true
paginate = 10
theme = "zzo"
disqusShortname = ""

# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
