baseURL = "//gatosyocora.net/"
title = "がとーしょこらの技術録"
theme = "zzo"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

summaryLength = 5
buildFuture = true

copyright = "Copyright © 2021, gatosyocora; all rights reserved."
timeout = 30000
enableEmoji = true
paginate = 10
rssLimit = 100

enableGitInfo = false
googleAnalytics = "G-8ETEKZT36Z"

languageCode = 'ja'
publishDir = 'docs'
disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
