[[main]]
  name = "ホーム"
  url = ""
  weight = -110

[[main]]
  identifier = "posts"
  name = "投稿"
  url = "posts"
  weight = -109

[[main]]
  identifier = "about"
  name = "関連情報"
  url = "about"
  weight = -107
