twitter = "@gatosyocora"
largeTwitterCard = false
introDescription = "UnityでVR関連のことをやっています"

numberOfTagsShown = 14

fallBackOgImage = "images/thumbnail.png"

codeMaxLines = 7

codeLineNumbers = false

enableMathNotation = false

mainSections = ["post"]

centerLogo = false

logo = ""

figurePositionShow = false
figurePositionLabel = "Figure"

mobileNavigation = "left"

enforceLightMode = false

footerLogo = "icons/copy.svg"

languageMenuName = "Lang"
 
iconsDir = "icons/"

[author]
name = "gatosyocora"
photo = "images/icon_ukon.jpg"